name: rdf_vocabularies_examples
description: Examples for RDF vocabulary packages
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  locorda_rdf_core: ^0.11.3
  locorda_rdf_terms_core: ^0.11.3
  locorda_rdf_terms_common: ^0.11.0
  locorda_rdf_terms_schema: ^0.11.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
