name: rdf_terms_generator_examples
description: Examples for locorda_rdf_terms_generator
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  locorda_rdf_core: ^0.11.3

dev_dependencies:
  locorda_rdf_terms_generator: ^0.11.3
  build_runner: ^2.10.5
  lints: ^6.0.0
  test: ^1.25.0
