name: mapper_annotations_examples
description: Examples for RDF Mapper Annotations
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  locorda_rdf_core: ^0.11.0
  locorda_rdf_mapper: ^0.11.2
  locorda_rdf_mapper_annotations: ^0.11.2
  locorda_rdf_terms_schema: ^0.11.0

dev_dependencies:
  build_runner: ^2.4.0
  locorda_rdf_mapper_generator: ^0.11.2
  test: ^1.25.0
